import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { auth, signOut } from '../../auth';
import prisma from './lib/prisma';
import Navbar from '@/components/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // auth checking
  const user =await auth();
  console.log("i am from layout",user);

  // fetching menus

  const menus = await prisma.menus.findMany();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="max-w-7xl mx-auto min-w-[300px] p-4">
          <Navbar user={user} menus={menus} />
          {children}
        </main>
      </body>
    </html>
  );
}
